services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - USER_ID=${UID:-1000}
                - GROUP_ID=${GID:-1000}
        container_name: iching_app
        restart: unless-stopped
        ports:
            - '5173:5173'
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ['CMD', 'php-fpm', '-t']
            interval: 5s
            timeout: 3s
            retries: 3
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Minsk
        networks:
            - iching_network

    nginx:
        image: nginx:1.25-alpine
        container_name: iching_nginx
        restart: unless-stopped
        ports:
            - '80:80'
            # - '443:443' # HTTPS
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/iching.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            app:
                condition: service_healthy # ждем готовности PHP
        networks:
            - iching_network

    db:
        image: mysql:8.0
        container_name: iching_db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Minsk
        ports:
            - '33061:3306'
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    'localhost',
                    '-u',
                    '${DB_USERNAME}',
                    '-p${DB_PASSWORD}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s
        networks:
            - iching_network

networks:
    iching_network:
        driver: bridge
volumes:
    db_data:
